### ISSUE TITLE
Better/easier installation instructions?

### ISSUE THREAD

**Issue by NeatNit** [AKSW/git_lfs_server_sshauth#1]
Hi,
I'm trying to set up a (very basic) git repository for me and a friend, and we require git LFS. I got plain ol' git working by simply giving both of us SSH access (as explained in https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server) but setting up Git LFS proves more tricky.

Had a look at the list of options in https://github.com/git-lfs/git-lfs/wiki/Implementations and yours seems probably the easiest to set up! Only problem is, I have no idea how to run it. I see that the main script is a .psgi file, but personally I've never heard of that and trying to look it up has led me down a rabbit hole, all of which kind of defeats the simplicity of this whole thing.

So could you add some more detailed setup instructions? Preferably something that doesn't assume anything is already installed.

I hope this isn't asking too much...

**Comment by SimonBin** [comment]
Hi @NeatNit I assume given the time that has passed this is no longer relevant to you?

**Comment by NeatNit** [comment]
> Hi @NeatNit I assume given the time that has passed this is no longer relevant to you?

Correct.

**Comment by SimonBin** [comment]
out of curiosity, did you find a good working LFS product?

**Comment by NeatNit** [comment]
I ended up installing GitLab for an all-in-one solution.
